using GestionITVPro.Enums;
using GestionITVPro.Models;

namespace GestionITVPro.Factory;

public static class CitasFactory {
    public static IEnumerable<Cita> Seed() {
        var hoy = DateTime.Today;

        return new List<Cita> {
            // --- 2024 (Pasadas/Borradas) ---
            new Cita { Id = 1, Matricula = "1001-AAA", Marca = "Toyota", Modelo = "Corolla", Cilindrada = 1800, Motor = Motor.Hibrido, DniPropietario = "12345678A", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2024, 02, 15), IsDeleted = true },
            new Cita { Id = 2, Matricula = "1002-BBB", Marca = "BMW", Modelo = "M3", Cilindrada = 3000, Motor = Motor.Gasolina, DniPropietario = "23456789B", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2024, 05, 20), IsDeleted = true },
            new Cita { Id = 3, Matricula = "1003-CCC", Marca = "Tesla", Modelo = "Model 3", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "34567890C", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2024, 08, 10), IsDeleted = true },
            new Cita { Id = 4, Matricula = "1004-DDD", Marca = "Audi", Modelo = "A3", Cilindrada = 2000, Motor = Motor.Diesel, DniPropietario = "45678901D", FechaItv = hoy.AddYears(-5), FechaInspeccion = new DateTime(2024, 11, 05), IsDeleted = true },
            new Cita { Id = 5, Matricula = "1005-EEE", Marca = "Seat", Modelo = "Leon", Cilindrada = 1500, Motor = Motor.Gasolina, DniPropietario = "56789012E", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2024, 12, 28), IsDeleted = true },
            new Cita { Id = 6, Matricula = "1006-FFF", Marca = "Ford", Modelo = "Focus", Cilindrada = 1600, Motor = Motor.Diesel, DniPropietario = "67890123F", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2024, 03, 12), IsDeleted = true },
            new Cita { Id = 7, Matricula = "1007-GGG", Marca = "Mercedes", Modelo = "Clase A", Cilindrada = 2000, Motor = Motor.Diesel, DniPropietario = "78901234G", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2024, 06, 18), IsDeleted = true },
            new Cita { Id = 8, Matricula = "1008-HHH", Marca = "Hyundai", Modelo = "Tucson", Cilindrada = 1600, Motor = Motor.Hibrido, DniPropietario = "89012345H", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2024, 09, 25), IsDeleted = true },
            new Cita { Id = 9, Matricula = "1009-III", Marca = "Kia", Modelo = "Sportage", Cilindrada = 1600, Motor = Motor.Diesel, DniPropietario = "90123456I", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2024, 01, 30), IsDeleted = true },
            new Cita { Id = 10, Matricula = "1010-JJJ", Marca = "Nissan", Modelo = "Qashqai", Cilindrada = 1300, Motor = Motor.Gasolina, DniPropietario = "01234567J", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2024, 04, 14), IsDeleted = true },
            new Cita { Id = 11, Matricula = "1011-KKK", Marca = "Volvo", Modelo = "XC40", Cilindrada = 1500, Motor = Motor.Hibrido, DniPropietario = "11223344K", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2024, 07, 22), IsDeleted = true },
            new Cita { Id = 12, Matricula = "1012-LLL", Marca = "Skoda", Modelo = "Octavia", Cilindrada = 2000, Motor = Motor.Diesel, DniPropietario = "22334455L", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2024, 10, 08), IsDeleted = true },
            new Cita { Id = 13, Matricula = "1013-MMM", Marca = "Honda", Modelo = "Civic", Cilindrada = 1500, Motor = Motor.Gasolina, DniPropietario = "33445566M", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2024, 11, 15), IsDeleted = true },
            new Cita { Id = 14, Matricula = "1014-NNN", Marca = "Mazda", Modelo = "CX-5", Cilindrada = 2200, Motor = Motor.Diesel, DniPropietario = "44556677N", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2024, 02, 28), IsDeleted = true },
            new Cita { Id = 15, Matricula = "1015-OOO", Marca = "Peugeot", Modelo = "3008", Cilindrada = 1200, Motor = Motor.Hibrido, DniPropietario = "55667788O", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2024, 05, 05), IsDeleted = true },
            new Cita { Id = 16, Matricula = "1016-PPP", Marca = "Renault", Modelo = "Austral", Cilindrada = 1300, Motor = Motor.Gasolina, DniPropietario = "66778899P", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2024, 08, 19), IsDeleted = true },
            new Cita { Id = 17, Matricula = "1017-QQQ", Marca = "Citroen", Modelo = "C4", Cilindrada = 1200, Motor = Motor.Diesel, DniPropietario = "77889900Q", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2024, 09, 11), IsDeleted = true },
            new Cita { Id = 18, Matricula = "1018-RRR", Marca = "Dacia", Modelo = "Sandero", Cilindrada = 1000, Motor = Motor.Gasolina, DniPropietario = "88990011R", FechaItv = hoy.AddYears(-5), FechaInspeccion = new DateTime(2024, 12, 02), IsDeleted = true },
            new Cita { Id = 19, Matricula = "1019-SSS", Marca = "Opel", Modelo = "Mokka", Cilindrada = 1200, Motor = Motor.Electrico, DniPropietario = "99001122S", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2024, 03, 24), IsDeleted = true },
            new Cita { Id = 20, Matricula = "1020-TTT", Marca = "Fiat", Modelo = "500", Cilindrada = 1000, Motor = Motor.Hibrido, DniPropietario = "00112233T", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2024, 06, 07), IsDeleted = true },

            // --- 2025 (Histórico Reciente) ---
            new Cita { Id = 21, Matricula = "1021-UUU", Marca = "Toyota", Modelo = "Yaris", Cilindrada = 1500, Motor = Motor.Hibrido, DniPropietario = "11223344U", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2025, 01, 15), IsDeleted = true },
            new Cita { Id = 22, Matricula = "1022-VVV", Marca = "BMW", Modelo = "X1", Cilindrada = 2000, Motor = Motor.Diesel, DniPropietario = "22334455V", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2025, 02, 20), IsDeleted = true },
            new Cita { Id = 23, Matricula = "1023-WWW", Marca = "Tesla", Modelo = "Model Y", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "33445566W", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2025, 03, 10), IsDeleted = true },
            new Cita { Id = 24, Matricula = "1024-XXX", Marca = "Audi", Modelo = "Q3", Cilindrada = 2000, Motor = Motor.Gasolina, DniPropietario = "44556677X", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2025, 04, 05), IsDeleted = true },
            new Cita { Id = 25, Matricula = "1025-YYY", Marca = "Seat", Modelo = "Ateca", Cilindrada = 1600, Motor = Motor.Diesel, DniPropietario = "55667788Y", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2025, 05, 12), IsDeleted = true },
            new Cita { Id = 26, Matricula = "1026-ZZZ", Marca = "Ford", Modelo = "Kuga", Cilindrada = 2500, Motor = Motor.Hibrido, DniPropietario = "66778899Z", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2025, 06, 18), IsDeleted = true },
            new Cita { Id = 27, Matricula = "1027-AAA", Marca = "Mercedes", Modelo = "GLC", Cilindrada = 2200, Motor = Motor.Diesel, DniPropietario = "77889900A", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2025, 07, 25), IsDeleted = true },
            new Cita { Id = 28, Matricula = "1028-BBB", Marca = "Hyundai", Modelo = "Ioniq", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "88990011B", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2025, 08, 30), IsDeleted = true },
            new Cita { Id = 29, Matricula = "1029-CCC", Marca = "Kia", Modelo = "Niro", Cilindrada = 1600, Motor = Motor.Hibrido, DniPropietario = "99001122C", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2025, 09, 14), IsDeleted = true },
            new Cita { Id = 30, Matricula = "1030-DDD", Marca = "Nissan", Modelo = "Juke", Cilindrada = 1000, Motor = Motor.Gasolina, DniPropietario = "00112233D", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2025, 10, 22), IsDeleted = true },
            new Cita { Id = 31, Matricula = "1031-EEE", Marca = "Volvo", Modelo = "XC60", Cilindrada = 2000, Motor = Motor.Diesel, DniPropietario = "11335577E", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2025, 11, 08), IsDeleted = true },
            new Cita { Id = 32, Matricula = "1032-FFF", Marca = "Skoda", Modelo = "Karoq", Cilindrada = 1500, Motor = Motor.Gasolina, DniPropietario = "22446688F", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2025, 12, 15), IsDeleted = true },
            new Cita { Id = 33, Matricula = "1033-GGG", Marca = "Honda", Modelo = "HR-V", Cilindrada = 1500, Motor = Motor.Hibrido, DniPropietario = "33557799G", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2025, 01, 20), IsDeleted = true },
            new Cita { Id = 34, Matricula = "1034-HHH", Marca = "Mazda", Modelo = "2", Cilindrada = 1500, Motor = Motor.Gasolina, DniPropietario = "44668800H", FechaItv = hoy.AddYears(-5), FechaInspeccion = new DateTime(2025, 02, 14), IsDeleted = true },
            new Cita { Id = 35, Matricula = "1035-III", Marca = "Peugeot", Modelo = "2008", Cilindrada = 1200, Motor = Motor.Gasolina, DniPropietario = "55779911I", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2025, 03, 05), IsDeleted = true },
            new Cita { Id = 36, Matricula = "1036-JJJ", Marca = "Renault", Modelo = "Captur", Cilindrada = 1300, Motor = Motor.Hibrido, DniPropietario = "66880022J", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2025, 04, 19), IsDeleted = true },
            new Cita { Id = 37, Matricula = "1037-KKK", Marca = "Citroen", Modelo = "C5", Cilindrada = 1600, Motor = Motor.Hibrido, DniPropietario = "77991133K", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2025, 05, 11), IsDeleted = true },
            new Cita { Id = 38, Matricula = "1038-LLL", Marca = "Lexus", Modelo = "UX", Cilindrada = 2000, Motor = Motor.Hibrido, DniPropietario = "88002244L", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2025, 06, 02), IsDeleted = true },
            new Cita { Id = 39, Matricula = "1039-MMM", Marca = "Toyota", Modelo = "RAV4", Cilindrada = 2500, Motor = Motor.Hibrido, DniPropietario = "99113355M", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2025, 07, 24), IsDeleted = true },
            new Cita { Id = 40, Matricula = "1040-NNN", Marca = "BMW", Modelo = "i4", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "00224466N", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2025, 08, 07), IsDeleted = true },

            // --- 2026 (Año Actual) ---
            new Cita { Id = 41, Matricula = "2041-AAA", Marca = "Renault", Modelo = "Clio", Cilindrada = 1200, Motor = Motor.Gasolina, DniPropietario = "41000001A", FechaItv = hoy.AddYears(-6), FechaInspeccion = new DateTime(2026, 01, 10), IsDeleted = false },
            new Cita { Id = 42, Matricula = "2042-BBB", Marca = "Peugeot", Modelo = "208", Cilindrada = 1400, Motor = Motor.Diesel, DniPropietario = "42000002B", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2026, 02, 15), IsDeleted = false },
            new Cita { Id = 43, Matricula = "2043-CCC", Marca = "Kia", Modelo = "Ceed", Cilindrada = 1600, Motor = Motor.Hibrido, DniPropietario = "43000003C", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2026, 03, 12), IsDeleted = false },
            new Cita { Id = 44, Matricula = "2044-DDD", Marca = "Hyundai", Modelo = "i30", Cilindrada = 1500, Motor = Motor.Gasolina, DniPropietario = "44000004D", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2026, 04, 20), IsDeleted = false },
            new Cita { Id = 45, Matricula = "2045-EEE", Marca = "Mazda", Modelo = "3", Cilindrada = 2000, Motor = Motor.Gasolina, DniPropietario = "45000005E", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2026, 05, 05), IsDeleted = false },
            new Cita { Id = 46, Matricula = "2046-FFF", Marca = "Nissan", Modelo = "Leaf", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "46000006F", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2026, 05, 10), IsDeleted = false },
            new Cita { Id = 47, Matricula = "2047-GGG", Marca = "Volvo", Modelo = "XC40", Cilindrada = 1500, Motor = Motor.Hibrido, DniPropietario = "47000007G", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2026, 05, 20), IsDeleted = false },
            new Cita { Id = 48, Matricula = "2048-HHH", Marca = "Skoda", Modelo = "Fabia", Cilindrada = 1000, Motor = Motor.Gasolina, DniPropietario = "48000008H", FechaItv = hoy.AddYears(-5), FechaInspeccion = new DateTime(2026, 06, 12), IsDeleted = false },
            new Cita { Id = 49, Matricula = "2049-III", Marca = "Fiat", Modelo = "500", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "49000009I", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2026, 07, 18), IsDeleted = false },
            new Cita { Id = 50, Matricula = "2050-JJJ", Marca = "Opel", Modelo = "Corsa", Cilindrada = 1200, Motor = Motor.Gasolina, DniPropietario = "50000010J", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2026, 08, 05), IsDeleted = false },
            new Cita { Id = 51, Matricula = "3051-AAA", Marca = "Porsche", Modelo = "Taycan", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "51000001A", FechaItv = hoy.AddYears(-2), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 52, Matricula = "3052-BBB", Marca = "Mercedes", Modelo = "Clase C", Cilindrada = 2000, Motor = Motor.Diesel, DniPropietario = "52000002B", FechaItv = hoy.AddYears(-3), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 53, Matricula = "3053-CCC", Marca = "Audi", Modelo = "A4", Cilindrada = 2000, Motor = Motor.Gasolina, DniPropietario = "53000003C", FechaItv = hoy.AddYears(-4), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 54, Matricula = "3054-DDD", Marca = "Toyota", Modelo = "Prius", Cilindrada = 1800, Motor = Motor.Hibrido, DniPropietario = "54000004D", FechaItv = hoy.AddYears(-5), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 55, Matricula = "3055-EEE", Marca = "BMW", Modelo = "iX", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "55000005E", FechaItv = hoy.AddYears(-1), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 56, Matricula = "3056-FFF", Marca = "Seat", Modelo = "Tarraco", Cilindrada = 2000, Motor = Motor.Diesel, DniPropietario = "56000006F", FechaItv = hoy.AddYears(-2), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 57, Matricula = "3057-GGG", Marca = "Ford", Modelo = "Mustang", Cilindrada = 5000, Motor = Motor.Gasolina, DniPropietario = "57000007G", FechaItv = hoy.AddYears(-3), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 58, Matricula = "3058-HHH", Marca = "Hyundai", Modelo = "Ioniq 5", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "58000008H", FechaItv = hoy.AddYears(-1), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 59, Matricula = "3059-III", Marca = "Kia", Modelo = "EV6", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "59000009I", FechaItv = hoy.AddYears(-1), FechaInspeccion = hoy, IsDeleted = false },
            new Cita { Id = 60, Matricula = "3060-JJJ", Marca = "Volkswagen", Modelo = "ID.4", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "60000010J", FechaItv = hoy.AddYears(-2), FechaInspeccion = hoy, IsDeleted = false },

            // --- 2027 (Citas a Largo Plazo) ---
            new Cita { Id = 61, Matricula = "3061-AAA", Marca = "Lexus", Modelo = "RX", Cilindrada = 3500, Motor = Motor.Hibrido, DniPropietario = "61000011A", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2027, 01, 15), IsDeleted = false },
            new Cita { Id = 62, Matricula = "3062-BBB", Marca = "Land Rover", Modelo = "Defender", Cilindrada = 3000, Motor = Motor.Diesel, DniPropietario = "62000012B", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2027, 02, 28), IsDeleted = false },
            new Cita { Id = 63, Matricula = "3063-CCC", Marca = "Jaguar", Modelo = "I-Pace", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "63000013C", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 03, 10), IsDeleted = false },
            new Cita { Id = 64, Matricula = "3064-DDD", Marca = "Alfa Romeo", Modelo = "Giulia", Cilindrada = 2000, Motor = Motor.Gasolina, DniPropietario = "64000014D", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2027, 04, 05), IsDeleted = false },
            new Cita { Id = 65, Matricula = "3065-EEE", Marca = "Jeep", Modelo = "Compass", Cilindrada = 1300, Motor = Motor.Hibrido, DniPropietario = "65000015E", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2027, 05, 12), IsDeleted = false },
            new Cita { Id = 66, Matricula = "3066-FFF", Marca = "Subaru", Modelo = "XV", Cilindrada = 2000, Motor = Motor.Hibrido, DniPropietario = "66000016F", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2027, 06, 18), IsDeleted = false },
            new Cita { Id = 67, Matricula = "3067-GGG", Marca = "Mitsubishi", Modelo = "ASX", Cilindrada = 1600, Motor = Motor.Hibrido, DniPropietario = "67000017G", FechaItv = hoy.AddYears(-3), FechaInspeccion = new DateTime(2027, 07, 25), IsDeleted = false },
            new Cita { Id = 68, Matricula = "3068-HHH", Marca = "Suzuki", Modelo = "Swift", Cilindrada = 1200, Motor = Motor.Hibrido, DniPropietario = "68000018H", FechaItv = hoy.AddYears(-4), FechaInspeccion = new DateTime(2027, 08, 30), IsDeleted = false },
            new Cita { Id = 69, Matricula = "3069-III", Marca = "Honda", Modelo = "e", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "69000019I", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 09, 14), IsDeleted = false },
            new Cita { Id = 70, Matricula = "3070-JJJ", Marca = "Mini", Modelo = "Cooper SE", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "70000020J", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2027, 10, 22), IsDeleted = false },
            new Cita { Id = 71, Matricula = "4071-AAA", Marca = "Lexus", Modelo = "NX", Cilindrada = 2500, Motor = Motor.Hibrido, DniPropietario = "71000001A", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 11, 08), IsDeleted = false },
            new Cita { Id = 72, Matricula = "4072-BBB", Marca = "Cupra", Modelo = "Born", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "72000002B", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 12, 15), IsDeleted = false },
            new Cita { Id = 73, Matricula = "4073-CCC", Marca = "Polestar", Modelo = "2", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "73000003C", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 01, 20), IsDeleted = false },
            new Cita { Id = 74, Matricula = "4074-DDD", Marca = "Tesla", Modelo = "Model S", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "74000004D", FechaItv = hoy.AddYears(-2), FechaInspeccion = new DateTime(2027, 02, 14), IsDeleted = false },
            new Cita { Id = 75, Matricula = "4075-EEE", Marca = "Porsche", Modelo = "911", Cilindrada = 3000, Motor = Motor.Gasolina, DniPropietario = "75000005E", FechaItv = hoy.AddYears(-5), FechaInspeccion = new DateTime(2027, 03, 05), IsDeleted = false },
            new Cita { Id = 76, Matricula = "4076-FFF", Marca = "Audi", Modelo = "e-tron", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "76000006F", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 04, 19), IsDeleted = false },
            new Cita { Id = 77, Matricula = "4077-GGG", Marca = "BMW", Modelo = "i7", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "77000007G", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 05, 11), IsDeleted = false },
            new Cita { Id = 78, Matricula = "4078-HHH", Marca = "Mercedes", Modelo = "EQS", Cilindrada = 0, Motor = Motor.Electrico, DniPropietario = "78000008H", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 06, 02), IsDeleted = false },
            new Cita { Id = 79, Matricula = "4079-III", Marca = "Maserati", Modelo = "Grecale", Cilindrada = 2000, Motor = Motor.Hibrido, DniPropietario = "79000009I", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 07, 24), IsDeleted = false },
            new Cita { Id = 80, Matricula = "4080-JJJ", Marca = "Ferrari", Modelo = "296 GTB", Cilindrada = 3000, Motor = Motor.Hibrido, DniPropietario = "80000010J", FechaItv = hoy.AddYears(-1), FechaInspeccion = new DateTime(2027, 08, 07), IsDeleted = false }
        };
    }
}